
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app



env_variables:
    CLOUD_SQL_CONNECTION_NAME: depapaya-225021:us-central1:depapaya
    DB_USER: root
    DB_PASS: D4c4t0.D3p4p4y4_2018!
    DB_NAME: depapaya

    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://root:D4c4t0.D3p4p4y4_2018!@/depapaya?unix_socket=/cloudsql/depapaya-225021:us-central1:depapaya

    SENDGRID_API_KEY: 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
    SENDGRID_SENDER: depapaya.web@gmail.com

beta_settings:
    cloud_sql_instances: depapaya-225021:us-central1:depapaya
